service:
  name: simple-s3-proxy

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2
  stage: production
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        - "arn:aws:s3:::${env:BUCKET_NAME}/*"

functions:
  put:
    handler: handler.put
    events:
      - http:
          method: put
          path: /{key}
  get:
    handler: handler.get
    events:
      - http:
          method: get
          path: /{key}
  delete:
    handler: handler.erase
    events:
      - http:
          method: delete
          path: /{key}

resources:
  Resources:
    ConfigBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}
